#!/usr/bin/env python3
"""
OPTUNA RUNNER v2.0 — 1 activo = 1 run (Regla de Oro Apr 4, 2026)

Modelo: Cada activo es un run independiente (~404 combos = 202 strats × 2 TFs).
  → ~14-23 min por activo en condiciones normales
  → Safety cap: 30 min por si acaso
  → Workers: 8 día / 10 noche (01:00-08:30)
  → Progreso guardado atómicamente entre activos

Uso:
  python3 scripts/optuna_runner.py                          # Modo auto — todos los activos
  python3 scripts/optuna_runner.py --symbols-file top50.txt # Solo activos de un archivo
  python3 scripts/optuna_runner.py --max-assets 10          # Solo los primeros 10
  python3 scripts/optuna_runner.py --tfs "1h,4h"            # Solo estos TFs
  python3 scripts/optuna_runner.py --dry-run                # Solo muestra config

Autor: Coordinadora + ESTRATEGIAS
Fecha: 2026-04-04
"""

import subprocess
import json
import os
import sys
import time
import signal
from datetime import datetime

# ─── CONFIG ───
ESTRATEGIAS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OPTUNA_SCRIPT = os.path.join(ESTRATEGIAS_DIR, "optuna_v7.py")
PROGRESS_FILE = os.path.join(ESTRATEGIAS_DIR, "data", "optuna_v7_progress.json")
SYMBOLS_CACHE = os.path.join(ESTRATEGIAS_DIR, "data", ".symbols_cache.json")
RUNNER_LOG_DIR = os.path.join(ESTRATEGIAS_DIR, "data", "runner_logs")
BUZON_DIR = os.path.join(os.path.dirname(ESTRATEGIAS_DIR), "BUZON")

DEFAULT_MAX_MINUTES = 30   # Safety cap per asset
WORKERS_DIURNO = 8         # 8:30am - 1:00am
WORKERS_NOCTURNO = 10      # 1:00am - 8:30am

os.makedirs(RUNNER_LOG_DIR, exist_ok=True)


def is_nocturno():
    """1:00 AM - 8:30 AM = nocturno."""
    h, m = datetime.now().hour, datetime.now().minute
    if h >= 1 and h < 8:
        return True
    if h == 8 and m <= 30:
        return True
    return False


def get_workers():
    w = WORKERS_NOCTURNO if is_nocturno() else WORKERS_DIURNO
    modo = "nocturno" if is_nocturno() else "diurno"
    return w, modo


def get_prioritized_assets():
    """Load symbols sorted by priority: production winners first, then by data volume."""
    # 1. Load from cache (generated by optuna_v7.py or pre-generated)
    if os.path.exists(SYMBOLS_CACHE):
        try:
            with open(SYMBOLS_CACHE) as f:
                cache = json.load(f)
            all_syms = cache.get('symbols', [])
            if all_syms:
                print(f"  Loaded {len(all_syms)} symbols from cache")
                return all_syms
        except Exception:
            pass

    # 2. Fallback: query DB directly (slow, ~5 min)
    print("  WARNING: No symbols cache found, querying DB...")
    import sqlite3, pandas as pd
    DB_PATH = "/Users/sabrina/Code/activos binace /activos_binance.db"
    if not os.path.exists(DB_PATH):
        DB_PATH = "/Users/sabrina/CLAUDE CODE/data/activos_binance.db"
    conn = sqlite3.connect(DB_PATH)
    df = pd.read_sql(
        "SELECT symbol, COUNT(*) as bars FROM candles "
        "WHERE timeframe='5m' GROUP BY symbol ORDER BY bars DESC", conn)
    conn.close()
    return df['symbol'].tolist()


def read_progress():
    """Read progress file and return done_combos set + grails count."""
    if not os.path.exists(PROGRESS_FILE):
        return set(), 0
    try:
        with open(PROGRESS_FILE) as f:
            data = json.load(f)
        return set(data.get('done_combos', [])), len(data.get('grails', []))
    except Exception:
        return set(), 0


def count_pending_for_asset(symbol, done_combos, tfs=None):
    """Count how many combos are pending for a given asset."""
    # We don't know exact strategy names here, so estimate based on done_combos patterns
    # A combo key is "strategy|symbol|tf"
    done_for_symbol = sum(1 for k in done_combos if f"|{symbol}|" in k)
    # Rough estimate: 202 strategies × len(tfs) TFs total per symbol
    n_tfs = len(tfs.split(',')) if tfs else 4  # default: 5m,15m,1h,4h
    estimated_total = 202 * n_tfs  # approximate
    return max(0, estimated_total - done_for_symbol), done_for_symbol


def run_one_asset(asset_num, total_assets, symbol, max_minutes, tfs=None, extra_args=None):
    """Run Optuna for ONE asset across specified TFs.

    If tfs is a comma-separated string (e.g. '1h,4h'), runs each TF sequentially.
    Each TF gets its own --tf flag and shares the safety cap proportionally.
    """
    workers, modo = get_workers()
    done_before, grails_before = read_progress()
    pending, already_done = count_pending_for_asset(symbol, done_before, tfs)

    if pending == 0:
        print(f"  [{asset_num}/{total_assets}] {symbol} -- SKIP (all combos done)")
        return {"symbol": symbol, "skipped": True, "reason": "all_done"}

    short_sym = symbol.split('/')[0]
    tf_list = tfs.split(',') if tfs else [None]  # None = use optuna default USE_TFS

    t0_total = time.time()
    total_combos = 0
    total_grails_new = 0
    any_timeout = False

    for tf_idx, tf in enumerate(tf_list):
        workers, modo = get_workers()  # Recalculate each TF (might cross day/night boundary)

        # Proportional time cap per TF
        if len(tf_list) > 1:
            tf_minutes = max(10, max_minutes // len(tf_list))  # At least 10 min per TF
        else:
            tf_minutes = max_minutes

        cmd = [
            sys.executable, OPTUNA_SCRIPT,
            "--symbol", symbol,
            "--workers", str(workers),
            "--max-minutes", str(tf_minutes),
        ]
        if tf:
            cmd.extend(["--tf", tf])
        if extra_args:
            cmd.extend(extra_args)

        tf_label = tf or "all"
        print(f"\n{'='*70}")
        print(f"[{asset_num}/{total_assets}] {short_sym}/{tf_label} | "
              f"{datetime.now().strftime('%H:%M:%S')} | Workers: {workers} ({modo}) | "
              f"Cap: {tf_minutes}min")
        print(f"{'='*70}")

        timed_out = False
        exit_code = -1
        t0 = time.time()

        try:
            proc = subprocess.Popen(
                cmd, stdout=sys.stdout, stderr=sys.stderr,
                cwd=ESTRATEGIAS_DIR,
            )
            timeout_s = (tf_minutes + 5) * 60
            try:
                exit_code = proc.wait(timeout=timeout_s)
            except subprocess.TimeoutExpired:
                timed_out = True
                any_timeout = True
                print(f"\n  [RUNNER] {short_sym}/{tf_label} timeout. SIGTERM...")
                proc.send_signal(signal.SIGTERM)
                try:
                    exit_code = proc.wait(timeout=30)
                except subprocess.TimeoutExpired:
                    proc.kill()
                    exit_code = proc.wait()
        except Exception as e:
            print(f"  [RUNNER] Error {short_sym}/{tf_label}: {e}")
            continue

        elapsed_tf = time.time() - t0
        done_now, grails_now = read_progress()
        combos_tf = len(done_now) - len(done_before)
        grails_tf = grails_now - grails_before
        total_combos += combos_tf
        total_grails_new += grails_tf
        done_before = done_now  # Update for next TF
        grails_before = grails_now

        status = "TIMEOUT" if timed_out else "OK"
        print(f"  {short_sym}/{tf_label}: +{combos_tf} combos, +{grails_tf} grails [{status}] "
              f"({elapsed_tf/60:.1f}min)")

    elapsed_total = time.time() - t0_total
    _, final_grails = read_progress()
    rate = total_combos / (elapsed_total / 60) if elapsed_total > 60 else total_combos

    result = {
        "symbol": symbol,
        "asset_num": asset_num,
        "elapsed_min": round(elapsed_total / 60, 1),
        "combos_done": total_combos,
        "grails_new": total_grails_new,
        "grails_total": final_grails,
        "rate_per_min": round(rate, 1),
        "workers": workers,
        "modo": modo,
        "timed_out": any_timeout,
        "tfs": tfs or "all",
    }

    emoji = "GRAIL" if total_grails_new > 0 else "OK"
    print(f"\n  [{emoji}] [{asset_num}/{total_assets}] {short_sym}: "
          f"+{total_combos} combos, +{total_grails_new} grails ({final_grails} total) "
          f"| {elapsed_total/60:.1f}min | {rate:.0f}/min")

    return result


def save_runner_log(results, start_time):
    """Save full runner session log."""
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_path = os.path.join(RUNNER_LOG_DIR, f"runner_v2_{ts}.json")
    completed = [r for r in results if not r.get('skipped')]
    with open(log_path, 'w') as f:
        json.dump({
            'version': '2.0',
            'model': '1_activo_1_run',
            'started': datetime.fromtimestamp(start_time).isoformat(),
            'finished': datetime.now().isoformat(),
            'total_assets': len(results),
            'assets_processed': len(completed),
            'assets_skipped': len(results) - len(completed),
            'total_combos': sum(r.get('combos_done', 0) for r in completed),
            'total_grails': sum(r.get('grails_new', 0) for r in completed),
            'total_time_min': round((time.time() - start_time) / 60, 1),
            'avg_rate': round(
                sum(r.get('rate_per_min', 0) for r in completed) / max(len(completed), 1), 1
            ),
            'results': results,
        }, f, indent=2, default=str)
    return log_path


def send_buzon(subject, body):
    """Send notification to coordinator."""
    os.makedirs(BUZON_DIR, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = os.path.join(BUZON_DIR, f"ESTRATEGIAS_PARA_COORDINADORA_{ts}.md")
    try:
        with open(path, 'w') as f:
            f.write(f"# {subject}\n**De**: optuna_runner v2\n**Fecha**: {datetime.now().isoformat()}\n\n{body}\n")
    except Exception:
        pass


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Optuna Runner v2 — 1 activo = 1 run")
    parser.add_argument("--max-minutes", type=int, default=DEFAULT_MAX_MINUTES,
                        help=f"Safety cap por activo (default: {DEFAULT_MAX_MINUTES})")
    parser.add_argument("--max-assets", type=int, default=0,
                        help="Máx activos a procesar (0=todos)")
    parser.add_argument("--symbols-file", type=str, default=None,
                        help="Archivo con lista de símbolos (1 por línea)")
    parser.add_argument("--tfs", type=str, default=None,
                        help="TFs separados por coma (default: usa USE_TFS de optuna_v7)")
    parser.add_argument("--skip-done", action="store_true", default=True,
                        help="Skip activos ya completados (default: True)")
    parser.add_argument("--trials", type=int, default=50,
                        help="Trials por combo (default: 50)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Solo muestra plan, no ejecuta")
    parser.add_argument("--pause", type=int, default=3,
                        help="Segundos entre activos (default: 3)")
    parser.add_argument("extra", nargs="*",
                        help="Args extra para optuna_v7.py")
    args = parser.parse_args()

    # ─── Load symbols ───
    if args.symbols_file:
        with open(args.symbols_file) as f:
            assets = [line.strip() for line in f if line.strip() and not line.startswith('#')]
        print(f"  Loaded {len(assets)} symbols from {args.symbols_file}")
    else:
        assets = get_prioritized_assets()

    if args.max_assets > 0:
        assets = assets[:args.max_assets]

    # ─── Estimate pending ───
    done_combos, grails_total = read_progress()
    workers, modo = get_workers()

    # Count done per asset
    asset_done_count = {}
    for k in done_combos:
        parts = k.split('|')
        if len(parts) >= 2:
            sym = parts[1]
            asset_done_count[sym] = asset_done_count.get(sym, 0) + 1

    n_tfs = len(args.tfs.split(',')) if args.tfs else 4
    est_per_asset = 202 * n_tfs  # approximate combos per asset
    pending_assets = []
    skipped_assets = []
    for sym in assets:
        done_for_sym = asset_done_count.get(sym, 0)
        if done_for_sym >= est_per_asset * 0.95:  # 95% threshold
            skipped_assets.append(sym)
        else:
            pending_assets.append(sym)

    total_pending_combos = len(pending_assets) * est_per_asset  # rough estimate
    est_time_per_asset = est_per_asset / 19  # ~19 combos/min average
    est_total_hours = len(pending_assets) * est_time_per_asset / 60

    # ─── Print plan ───
    print(f"\n{'='*70}")
    print(f"OPTUNA RUNNER v2.0 — 1 ACTIVO = 1 RUN")
    print(f"{'='*70}")
    print(f"  Activos totales:    {len(assets)}")
    print(f"  Ya completados:     {len(skipped_assets)}")
    print(f"  Pendientes:         {len(pending_assets)}")
    print(f"  Combos estimados:   ~{total_pending_combos:,}")
    print(f"  ETA estimado:       ~{est_total_hours:.0f}h ({est_total_hours/24:.1f} días)")
    print(f"  Safety cap:         {args.max_minutes} min/activo")
    print(f"  Workers:            {workers} ({modo}) — recalcula cada activo")
    print(f"  Trials:             {args.trials}")
    print(f"  Progress file:      {PROGRESS_FILE}")
    print(f"  Done combos:        {len(done_combos)}")
    print(f"  Grails acumulados:  {grails_total}")
    if args.tfs:
        print(f"  TFs:                {args.tfs}")
    if pending_assets:
        print(f"\n  Próximos 5 activos:")
        for i, sym in enumerate(pending_assets[:5]):
            done = asset_done_count.get(sym, 0)
            print(f"    {i+1}. {sym} ({done}/{est_per_asset} done)")
    print(f"{'='*70}")

    if args.dry_run:
        print("\n[DRY-RUN] No se ejecuta nada. Revisá el plan arriba.")
        return

    # ─── Execute ───
    start_time = time.time()
    all_results = []
    extra = args.extra or []
    if args.trials != 50:
        extra.extend(["--trials", str(args.trials)])

    for i, symbol in enumerate(pending_assets, 1):
        result = run_one_asset(
            asset_num=i,
            total_assets=len(pending_assets),
            symbol=symbol,
            max_minutes=args.max_minutes,
            tfs=args.tfs,
            extra_args=extra if extra else None,
        )
        all_results.append(result)

        # Check if timed out (unusual — asset has too much data)
        if result.get('timed_out'):
            print(f"  ⚠️ {symbol} hit {args.max_minutes}min cap — unusual. Continuing to next asset.")

        # Pause between assets (let system breathe)
        if i < len(pending_assets):
            time.sleep(args.pause)

    # ─── Summary ───
    elapsed_total = time.time() - start_time
    completed = [r for r in all_results if not r.get('skipped') and not r.get('error')]
    total_combos = sum(r.get('combos_done', 0) for r in completed)
    total_grails = sum(r.get('grails_new', 0) for r in completed)
    _, final_grails = read_progress()

    log_path = save_runner_log(all_results, start_time)

    print(f"\n{'='*70}")
    print(f"OPTUNA RUNNER v2.0 — RESUMEN FINAL")
    print(f"{'='*70}")
    print(f"  Activos procesados: {len(completed)}/{len(pending_assets)}")
    print(f"  Combos totales:     +{total_combos:,}")
    print(f"  Grails nuevos:      +{total_grails}")
    print(f"  Grails acumulados:  {final_grails}")
    print(f"  Tiempo total:       {elapsed_total/60:.0f} min ({elapsed_total/3600:.1f}h)")
    if total_combos > 0:
        print(f"  Rate promedio:      {total_combos/(elapsed_total/60):.1f} combos/min")
    print(f"  Log:                {log_path}")
    print(f"{'='*70}")

    # Notify BUZON
    send_buzon(
        f"Runner v2 completado: +{total_combos} combos, +{total_grails} grails",
        f"Activos: {len(completed)}/{len(pending_assets)} | "
        f"Tiempo: {elapsed_total/60:.0f}min | Grails total: {final_grails}"
    )


if __name__ == "__main__":
    main()
